# Generated by Django 6.1.1 on 2026-09-18 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_requested_by_patient_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked out'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('created_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to='users.hospitalstaffprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.patientprofile')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=255)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='users.patientprofile')),
                ('prescribed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_medications', to='users.hospitalstaffprofile')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='visits.visit')),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vitals', to='users.hospitalstaffprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='visits.visit')),
            ],
            options={
                'db_table': 'vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'admitted_at'], name='visits_patient_44fc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['hospital', 'status'], name='visits_hospita_271d10_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'status'], name='medications_patient_9bf09f_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'created_at'], name='medications_patient_3e8ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='vital',
            index=models.Index(fields=['visit', 'recorded_at'], name='vitals_visit_i_ff9c26_idx'),
        ),
    ]
