# Generated by Django 6.1.1 on 2026-09-18 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('verification_status', models.CharField(choices=[('self_reported', 'Self-reported'), ('doctor_verified', 'Doctor-verified')], default='self_reported', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_medical_records', to='users.hospitalstaffprofile')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='users.patientprofile')),
                ('supersedes_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_entries', to='records.medicalrecord')),
                ('verified_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_medical_records', to='users.hospitalstaffprofile')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='visits.visit')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='medical_rec_patient_bfaf9b_idx'), models.Index(fields=['patient', 'entry_type'], name='medical_rec_patient_a2c317_idx'), models.Index(fields=['verification_status'], name='medical_rec_verific_0550a5_idx')],
            },
        ),
    ]
