# Generated by Django 6.1.1 on 2026-09-18 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        ('visits', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('access_level', models.CharField(choices=[('critical_info_only', 'Critical information only'), ('full_record', 'Full record')], default='full_record', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('code', models.CharField(editable=False, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('patient_response_deadline', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='users.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='users.patientprofile')),
                ('requested_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='users.hospitalstaffprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='visits.visit')),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('critical_info_only', 'Critical information only'), ('full_record', 'Full record')], max_length=30)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.CharField(choices=[('patient', 'Patient'), ('emergency_contact', 'Emergency contact')], max_length=30)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.CharField(blank=True, choices=[('patient', 'Patient'), ('system', 'System / checkout'), ('escalation', 'Escalation')], max_length=30, null=True)),
                ('access_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grant', to='access.accessrequest')),
            ],
            options={
                'db_table': 'access_grants',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority_order', models.PositiveSmallIntegerField(default=1)),
                ('response_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='users.patientprofile')),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('patient_notified', 'Patient notified'), ('emergency_contact_notified', 'Emergency contact notified')], max_length=40)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('access_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escalation', to='access.accessrequest')),
            ],
            options={
                'db_table': 'emergency_escalations',
            },
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['patient', 'status'], name='access_requ_patient_c7c448_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['hospital', 'status'], name='access_requ_hospita_568182_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['visit', 'status'], name='access_requ_visit_i_94e930_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['revoked_at'], name='access_gran_revoked_234bda_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyescalation',
            index=models.Index(fields=['stage', 'resolved_at'], name='emergency_e_stage_822ea7_idx'),
        ),
    ]
