# Generated by Django 6.1.1 on 2026-09-18 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='users.patientprofile')),
            ],
            options={
                'db_table': 'patient_cards',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patient_car_patient_7d472d_idx'), models.Index(fields=['card_reference'], name='patient_car_card_re_35d137_idx'), models.Index(fields=['expires_at'], name='patient_car_expires_f5e022_idx')],
            },
        ),
    ]
